/*
 * LoginDialog.java
 */
package org.oki.elv.client.gui;

import java.awt.Frame;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import org.jdesktop.application.Action;
import org.jdesktop.application.Application;
import org.jdesktop.application.ResourceMap;
import org.oki.elv.common.face.Person;

/**
 * Login dialog.
 * @author Elv
 */
public class LoginDialog extends JDialog {
  /** Existing persons. */
  List<Person> persons; 
  
  /** Logged person. */
  private Person loggedPerson;
  /** Count of maximum login attempts. */
  private int attemptCount = 2;
  
  /**
   * Constructor.
   */
  public LoginDialog(List<Person> persons) {
    super((Frame)null, true);
    this.persons = persons;
    initComponents();
    getRootPane().setDefaultButton(okButton);
  }

  /**
   * Getter of logged person.
   * @return the logged person.
   */
  public Person getLoggedPerson() {
    return loggedPerson;
  }
  
  /** OK action. */
  @Action
  public void ok() {
    ResourceMap resourceMap = Application.getInstance(App.class).getContext().getResourceMap(LoginDialog.class);
    String incorrectLoginTitle = resourceMap.getString("incorrectLogin.title");
    String incorrectLoginMessage = resourceMap.getString("incorrectLogin.message");
    String incorrectLoginExitMessage = resourceMap.getString("incorrectLogin.exitMessage");
    try {
      if(attemptCount > 0) {
        loggedPerson = Person.findNamedPerson(persons, nameTextField.getText());
        if(loggedPerson != null && loggedPerson.getPassword().equals(String.valueOf(passwordPasswordField.getPassword()))) {
          setVisible(false);
          dispose();
        }
        else {
          JOptionPane.showMessageDialog(this, incorrectLoginMessage, incorrectLoginTitle, JOptionPane.ERROR_MESSAGE);
          nameTextField.selectAll();
          nameTextField.requestFocusInWindow();
          passwordPasswordField.setText(null);
          attemptCount--;
        }
      }
      else {
        JOptionPane.showMessageDialog(this, incorrectLoginExitMessage, incorrectLoginTitle, JOptionPane.ERROR_MESSAGE);
        System.exit(1);
      }
    }
    catch(Exception exc) {
      Dialogs.showException(this, exc);
      System.exit(1);
    }
  }
  
  /** Cancel action. */
  @Action
  public void cancel() {
    setVisible(false);
    dispose();
    System.exit(0);
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    iconLabel = new javax.swing.JLabel();
    nameLabel = new javax.swing.JLabel();
    nameTextField = new javax.swing.JTextField();
    passwordLabel = new javax.swing.JLabel();
    okButton = new javax.swing.JButton();
    cancelButton = new javax.swing.JButton();
    passwordPasswordField = new javax.swing.JPasswordField();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(org.oki.elv.client.gui.App.class).getContext().getResourceMap(LoginDialog.class);
    setTitle(resourceMap.getString("loginDialog.title")); // NOI18N
    setName("loginDialog"); // NOI18N

    iconLabel.setName("iconLabel"); // NOI18N

    nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    nameLabel.setText(resourceMap.getString("nameLabel.text")); // NOI18N
    nameLabel.setName("nameLabel"); // NOI18N

    nameTextField.setName("nameTextField"); // NOI18N

    passwordLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    passwordLabel.setText(resourceMap.getString("passwordLabel.text")); // NOI18N
    passwordLabel.setName("passwordLabel"); // NOI18N

    javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(org.oki.elv.client.gui.App.class).getContext().getActionMap(LoginDialog.class, this);
    okButton.setAction(actionMap.get("ok")); // NOI18N
    okButton.setText(resourceMap.getString("okButton.text")); // NOI18N
    okButton.setName("okButton"); // NOI18N

    cancelButton.setAction(actionMap.get("cancel")); // NOI18N
    cancelButton.setText(resourceMap.getString("cancelButton.text")); // NOI18N
    cancelButton.setName("cancelButton"); // NOI18N

    passwordPasswordField.setName("passwordPasswordField"); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(okButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(cancelButton))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(nameLabel))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(passwordPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
              .addComponent(nameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))))
        .addContainerGap())
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
          .addContainerGap(51, Short.MAX_VALUE)
          .addComponent(iconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addContainerGap()))
    );

    layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(58, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(nameLabel)
          .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(passwordPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(passwordLabel))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(okButton)
          .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap())
      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
          .addContainerGap()
          .addComponent(iconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addContainerGap(123, Short.MAX_VALUE)))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton cancelButton;
  private javax.swing.JLabel iconLabel;
  private javax.swing.JLabel nameLabel;
  private javax.swing.JTextField nameTextField;
  private javax.swing.JButton okButton;
  private javax.swing.JLabel passwordLabel;
  private javax.swing.JPasswordField passwordPasswordField;
  // End of variables declaration//GEN-END:variables
}
