/*
 * LoginDialog.java
 */
package elv.gui;

/**
 * Dialog for loggin in.
 * @author Qpa
 */
public class LoginDialog extends javax.swing.JDialog
{
  /**
   * Variables.
   */
  private java.util.Vector<elv.util.User> users;
  
  private int tryCount = 2;
  private elv.util.User actualUser = null;
  
  /**
   * Constructor.
   * @param title the title of this wizard dialog.
   */
  public LoginDialog(java.lang.String title, java.util.Vector<elv.util.User> users)
  {
    super((java.awt.Frame)null, title, true);
    this.users = users;
    try
    {
      initComponents();
      okButton.getRootPane().setDefaultButton(okButton);
    }
    catch(java.lang.Exception exc)
    {
      elv.util.Error.showErrorMessage(this, exc);
    }
  }
  
  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  private void initComponents()//GEN-BEGIN:initComponents
  {
    mainPanel = new javax.swing.JPanel();
    imagePanel = new javax.swing.JPanel();
    imageLabel = new javax.swing.JLabel();
    loginContentPanel = new javax.swing.JPanel();
    labelsPanel = new javax.swing.JPanel();
    nameLabel = new javax.swing.JLabel();
    passwordLabel = new javax.swing.JLabel();
    inputsPanel = new javax.swing.JPanel();
    nameTextField = new javax.swing.JTextField();
    passwordPasswordField = new javax.swing.JPasswordField();
    buttonsOrientationPanel = new javax.swing.JPanel();
    mainSeparator = new javax.swing.JSeparator();
    buttonsPanel = new javax.swing.JPanel();
    okButton = new javax.swing.JButton();
    cancelButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setModal(true);
    setResizable(false);
    addWindowListener(new java.awt.event.WindowAdapter()
    {
      public void windowClosing(java.awt.event.WindowEvent evt)
      {
        closeDialog(evt);
      }
    });

    mainPanel.setLayout(new java.awt.BorderLayout());

    imagePanel.setLayout(new java.awt.BorderLayout());

    imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/login.gif")));
    imagePanel.add(imageLabel, java.awt.BorderLayout.CENTER);

    mainPanel.add(imagePanel, java.awt.BorderLayout.NORTH);

    loginContentPanel.setLayout(new java.awt.BorderLayout());

    labelsPanel.setLayout(new java.awt.GridLayout(0, 1, 0, 10));

    labelsPanel.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(10, 10, 10, 10)));
    nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    nameLabel.setLabelFor(nameTextField);
    nameLabel.setText(elv.util.Util.translate(elv.util.Util.NAME) + ":");
    labelsPanel.add(nameLabel);

    passwordLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
    passwordLabel.setLabelFor(passwordPasswordField);
    passwordLabel.setText(elv.util.Util.translate(elv.util.User.PASSWORD_NAME) + ":");
    labelsPanel.add(passwordLabel);

    loginContentPanel.add(labelsPanel, java.awt.BorderLayout.WEST);

    inputsPanel.setLayout(new java.awt.GridLayout(0, 1, 0, 10));

    inputsPanel.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(10, 1, 10, 10)));
    inputsPanel.add(nameTextField);

    passwordPasswordField.setFont(new java.awt.Font("DialogInput", 0, 12));
    passwordPasswordField.setEchoChar(elv.util.Util.PASSWORD_ECHO_CHAR);
    inputsPanel.add(passwordPasswordField);

    loginContentPanel.add(inputsPanel, java.awt.BorderLayout.CENTER);

    mainPanel.add(loginContentPanel, java.awt.BorderLayout.CENTER);

    getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

    buttonsOrientationPanel.setLayout(new java.awt.BorderLayout());

    buttonsOrientationPanel.add(mainSeparator, java.awt.BorderLayout.NORTH);

    buttonsPanel.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

    buttonsPanel.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(10, 10, 10, 10)));
    okButton.setText(new elv.util.Action(elv.util.Action.OK).toString());
    okButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        okButtonActionPerformed(evt);
      }
    });

    buttonsPanel.add(okButton);

    cancelButton.setText(new elv.util.Action(elv.util.Action.CANCEL).toString());
    cancelButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        cancelButtonActionPerformed(evt);
      }
    });

    buttonsPanel.add(cancelButton);

    buttonsOrientationPanel.add(buttonsPanel, java.awt.BorderLayout.EAST);

    getContentPane().add(buttonsOrientationPanel, java.awt.BorderLayout.SOUTH);

    pack();
    java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
    java.awt.Dimension dialogSize = getSize();
    setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
  }//GEN-END:initComponents

  private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelButtonActionPerformed
  {//GEN-HEADEREND:event_cancelButtonActionPerformed
    cancelAction();
  }//GEN-LAST:event_cancelButtonActionPerformed

  private void okButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_okButtonActionPerformed
  {//GEN-HEADEREND:event_okButtonActionPerformed
    okAction();
  }//GEN-LAST:event_okButtonActionPerformed

  private void closeDialog(java.awt.event.WindowEvent evt)//GEN-FIRST:event_closeDialog
  {//GEN-HEADEREND:event_closeDialog
    cancelAction();
  }//GEN-LAST:event_closeDialog
  
  /**
   * Method for ok action.
   */
  private void okAction()
  {
    try
    {
      if(tryCount > 0)
      {
        actualUser = elv.util.User.get(nameTextField.getText(), users);
        if(actualUser != null && 
           elv.util.Property.get(elv.util.User.PASSWORD_NAME, actualUser.getProperties()).getValue().equals(java.lang.String.valueOf(passwordPasswordField.getPassword())))
        {
          setVisible(false);
          dispose();
        }
        else
        {
          javax.swing.JOptionPane.showMessageDialog(this, elv.util.Util.translate(elv.util.Util.LOGIN_STATEMENT), new elv.util.State(elv.util.State.ERROR).toString(), javax.swing.JOptionPane.ERROR_MESSAGE);
          nameTextField.selectAll();
          nameTextField.requestFocusInWindow();
          passwordPasswordField.setText(null);
          tryCount--;
        }
      }
      else
      {
        javax.swing.JOptionPane.showMessageDialog(this, "Bye-bye!!!", new elv.util.State(elv.util.State.ERROR).toString(), javax.swing.JOptionPane.ERROR_MESSAGE);
        java.lang.System.exit(1);
      }
    }
    catch(java.lang.Exception exc)
    {
      elv.util.Error.showErrorMessage(this, exc);
      java.lang.System.exit(1);
    }
  }
  
  /**
   * Method for cancel action.
   */
  private void cancelAction()
  {
    setVisible(false);
    dispose();
    java.lang.System.exit(0);
  }
  
  /**
   * Method for get the logged user.
   */
  public elv.util.User getUser()
  {
    return actualUser;
  }
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel buttonsOrientationPanel;
  private javax.swing.JPanel buttonsPanel;
  private javax.swing.JButton cancelButton;
  private javax.swing.JLabel imageLabel;
  private javax.swing.JPanel imagePanel;
  private javax.swing.JPanel inputsPanel;
  private javax.swing.JPanel labelsPanel;
  private javax.swing.JPanel loginContentPanel;
  private javax.swing.JPanel mainPanel;
  private javax.swing.JSeparator mainSeparator;
  private javax.swing.JLabel nameLabel;
  private javax.swing.JTextField nameTextField;
  private javax.swing.JButton okButton;
  private javax.swing.JLabel passwordLabel;
  private javax.swing.JPasswordField passwordPasswordField;
  // End of variables declaration//GEN-END:variables
 
}
