/*
 * LoginDialog.java
 */
package elv.gui;

/**
 * Dialog for loggin in.
 * @author Elv
 */
public class AboutDialog extends javax.swing.JDialog
{
  /**
   * Constructor.
   * @param title the title of this wizard dialog.
   */
  public AboutDialog(java.lang.String title)
  {
    super(elv.util.Util.getMainFrame(), title, true);
    try
    {
      initComponents();
      java.awt.Dimension windowSize = elv.util.Util.getMainFrame().getSize();
      java.awt.Point windowLocation = elv.util.Util.getMainFrame().getLocation();
      java.awt.Dimension dialogSize = getSize();
      java.awt.Point dialogLocation = new java.awt.Point(windowLocation.x + (windowSize.width-dialogSize.width)/2, windowLocation.y + (windowSize.height-dialogSize.height)/2);
      setLocation((dialogLocation.x >= 0 ? dialogLocation.x : 0), (dialogLocation.y >= 0 ? dialogLocation.y : 0));
      okButton.getRootPane().setDefaultButton(okButton);
    }
    catch(java.lang.Exception exc)
    {
      elv.util.Error.showErrorMessage(this, exc);
    }
  }
  
  /**
   * This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private void initComponents()
  {
    mainPanel = new javax.swing.JPanel();
    imageLabel = new javax.swing.JLabel();
    buttonPanel = new javax.swing.JPanel();
    okButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setModal(true);
    setResizable(false);
    addWindowListener(new java.awt.event.WindowAdapter()
    {
      public void windowClosing(java.awt.event.WindowEvent evt)
      {
        closeDialog(evt);
      }
    });

    mainPanel.setLayout(new java.awt.BorderLayout());

    imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/splash.gif")));
    mainPanel.add(imageLabel, java.awt.BorderLayout.CENTER);

    getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

    buttonPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
    okButton.setText(new elv.util.Action(elv.util.Action.OK).toString());
    okButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        okButtonActionPerformed(evt);
      }
    });

    buttonPanel.add(okButton);

    getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

    pack();
  }
  // </editor-fold>//GEN-END:initComponents

  private void okButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_okButtonActionPerformed
  {//GEN-HEADEREND:event_okButtonActionPerformed
    okAction();
  }//GEN-LAST:event_okButtonActionPerformed

  private void closeDialog(java.awt.event.WindowEvent evt)//GEN-FIRST:event_closeDialog
  {//GEN-HEADEREND:event_closeDialog
    okAction();
  }//GEN-LAST:event_closeDialog
  
  /**
   * Method for cancel action.
   */
  private void okAction()
  {
    setVisible(false);
    dispose();
  }
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel buttonPanel;
  private javax.swing.JLabel imageLabel;
  private javax.swing.JPanel mainPanel;
  private javax.swing.JButton okButton;
  // End of variables declaration//GEN-END:variables
 
}
